/** Import failed: Mammoth/parse produced no constructor sections. */
export const CONSTRUCTOR_IMPORT_NO_CONTENT = 'CONSTRUCTOR_IMPORT_NO_CONTENT';

/** Stable import warning codes returned alongside Mammoth messages. */
export const CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN =
  'CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN';
export const CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN =
  'CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN';
export const CONSTRUCTOR_IMPORT_EQUATION_LOST = 'CONSTRUCTOR_IMPORT_EQUATION_LOST';
export const CONSTRUCTOR_IMPORT_MAMMOTH_NOTES =
  'CONSTRUCTOR_IMPORT_MAMMOTH_NOTES';

export const CONSTRUCTOR_IMPORT_WARNING_CODES = [
  CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN,
  CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN,
  CONSTRUCTOR_IMPORT_EQUATION_LOST,
  CONSTRUCTOR_IMPORT_MAMMOTH_NOTES,
] as const;

export type ConstructorImportWarningCode =
  (typeof CONSTRUCTOR_IMPORT_WARNING_CODES)[number];
