// AUTO-GENERATED by perf/scripts/generate-k6-thresholds.mjs — do not edit.
export const thresholdsConfig = {
  "profiles": {
    "local": {
      "emailPipeline": {
        "drainSecondsMax": 150
      }
    },
    "ci": {}
  },
  "reviewSubmit": {
    "httpReqDurationP95Ms": 2000,
    "httpReqDurationP99Ms": 5000,
    "httpReqFailedRate": 0.01,
    "checksRateMin": 0.99
  },
  "emailPipeline": {
    "drainSecondsMax": 150,
    "inviteCount": 50,
    "minThroughputPerSecond": 0.3
  },
  "aiGrpc": {
    "syncRpcP95Ms": 500,
    "corpusJobsCount": 10,
    "corpusJobsDrainSecondsMax": 180
  },
  "editorQueue": {
    "vus": 10,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 1000,
    "httpReqFailedRate": 0.01
  },
  "reviewerInbox": {
    "vus": 10,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 1000,
    "httpReqFailedRate": 0.01
  },
  "authLogin": {
    "vus": 20,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 2000,
    "httpReqFailedRate": 0.05
  },
  "publicSearch": {
    "vus": 15,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 1500,
    "httpReqFailedRate": 0.01
  },
  "notifications": {
    "vus": 10,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 1000,
    "httpReqFailedRate": 0.01
  },
  "submissionDetail": {
    "vus": 10,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 2000,
    "httpReqFailedRate": 0.01
  },
  "fileUpload": {
    "vus": 5,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 5000,
    "httpReqFailedRate": 0.05
  },
  "auditStress": {
    "vus": 10,
    "durationSeconds": 30,
    "httpReqDurationP95Ms": 1500,
    "httpReqFailedRate": 0.01
  },
  "poolStress": {
    "httpReqFailedRate": 0.05,
    "httpReqDurationMaxMs": 30000
  },
  "soak": {
    "durationMinutes": 30,
    "arrivalRatePerSecond": 5,
    "httpReqFailedRate": 0.001,
    "p95DriftPercentMax": 30
  },
  "typesense": {
    "rps": 50,
    "durationSeconds": 30,
    "searchP95Ms": 100
  },
  "database": {
    "slowQueryP95Ms": 500,
    "maxSeqScanRatio": 0.1,
    "topQueryCount": 20,
    "hotTables": [
      "submissions",
      "review_assignments",
      "audit_log",
      "outbound_event_outbox"
    ]
  },
  "queryBudgets": {
    "editorQueueList": 50,
    "reviewerInboxList": 50,
    "reviewSubmitTx": 200,
    "assignmentBySlug": 25,
    "outboxClaim": 100
  },
  "regression": {
    "maxP95DriftPercent": 20
  }
};

export const k6Thresholds = {
  "reviewSubmit": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:review_submit}": [
      "p(95)<2000",
      "p(99)<5000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "emailPipeline": {
    "email_pipeline_drain_seconds": [
      "max<150"
    ],
    "email_pipeline_throughput_per_sec": [
      "min>0.3"
    ]
  },
  "editorQueue": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:editor_queue}": [
      "p(95)<1000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "reviewerInbox": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:reviewer_inbox}": [
      "p(95)<1000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "authLogin": {
    "http_req_failed": [
      "rate<0.05"
    ],
    "http_req_duration{endpoint:auth_login}": [
      "p(95)<2000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "publicSearch": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:public_search}": [
      "p(95)<1500"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "notifications": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:notifications}": [
      "p(95)<1000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "submissionDetail": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:submission_detail}": [
      "p(95)<2000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "fileUpload": {
    "http_req_failed": [
      "rate<0.05"
    ],
    "http_req_duration{endpoint:file_upload}": [
      "p(95)<5000"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "auditStress": {
    "http_req_failed": [
      "rate<0.01"
    ],
    "http_req_duration{endpoint:audit_stress}": [
      "p(95)<1500"
    ],
    "checks": [
      "rate>0.99"
    ]
  },
  "poolStress": {
    "http_req_failed": [
      "rate<0.05"
    ],
    "http_req_duration": [
      "max<30000"
    ]
  },
  "soak": {
    "http_req_failed": [
      "rate<0.001"
    ]
  }
};

export function suiteThresholds(suiteName) {
  return k6Thresholds[suiteName] ?? {};
}

export function suiteConfig(suiteName) {
  return thresholdsConfig[suiteName] ?? {};
}

export const activeProfile = "local";
