export const CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN =
  "CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN";
export const CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN =
  "CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN";
export const CONSTRUCTOR_IMPORT_EQUATION_LOST = "CONSTRUCTOR_IMPORT_EQUATION_LOST";

export const CONSTRUCTOR_IMPORT_WARNING_CODES = [
  CONSTRUCTOR_IMPORT_TABLE_NOTE_UNCERTAIN,
  CONSTRUCTOR_IMPORT_BACK_MATTER_UNCERTAIN,
  CONSTRUCTOR_IMPORT_EQUATION_LOST,
] as const;

export type ConstructorImportWarningCode =
  (typeof CONSTRUCTOR_IMPORT_WARNING_CODES)[number];

export function isImportWarningCode(value: string): value is ConstructorImportWarningCode {
  return (CONSTRUCTOR_IMPORT_WARNING_CODES as readonly string[]).includes(value);
}
