/** Backend `code` values for submission submit / metadata failures (localized in SubmissionWorkflow). */
export const SUBMISSION_API_ERROR_CODES = [
  "SUBMISSION_INCOMPLETE_ARTICLE_TYPE",
  "SUBMISSION_INCOMPLETE_KEYWORDS",
  "SUBMISSION_INCOMPLETE_KEYWORDS_AR",
  "SUBMISSION_INCOMPLETE_TITLE_AR",
  "SUBMISSION_INCOMPLETE_CONTRIBUTORS",
  "SUBMISSION_INCOMPLETE_CORRESPONDING",
  "SUBMISSION_INCOMPLETE_CONTRIBUTOR_FIELDS",
  "SUBMISSION_INCOMPLETE_ORIGINALITY",
  "SUBMISSION_INCOMPLETE_COI",
  "SUBMISSION_INCOMPLETE_ETHICS",
  "SUBMISSION_INCOMPLETE_AI",
  "SUBMISSION_INCOMPLETE_ABSTRACT",
  "SUBMISSION_INCOMPLETE_ABSTRACT_AR",
  "SUBMISSION_INCOMPLETE_FILES",
  "SUBMISSION_ABSTRACT_TOO_LONG_EN",
  "SUBMISSION_ABSTRACT_TOO_LONG_AR",
  "SUBMISSION_MANUSCRIPT_PRESENTATION_REQUIRED",
  "SUBMISSION_SLUG_TAKEN",
] as const;

export type SubmissionApiErrorCode = (typeof SUBMISSION_API_ERROR_CODES)[number];

export function submissionApiErrorMessageKey(
  code: SubmissionApiErrorCode,
): `error_${SubmissionApiErrorCode}` {
  return `error_${code}`;
}
